export const COMMON_FEATURES = [
    "Hardwood Floors",
    "Stainless Steel Appliances",
    "Granite Countertops",
    "Walk-in Closet",
    "Balcony/Patio",
    "In-unit Laundry",
    "Dishwasher",
    "Air Conditioning",
    "Heating",
    "Fireplace",
    "Garage",
    "Parking",
    "Garden/Yard",
    "Swimming Pool",
    "Gym/Fitness Center",
    "Elevator",
    "Doorman/Concierge",
    "Pet Friendly",
    "Storage Unit",
    "High Ceilings",
    "Large Windows",
    "City Views",
    "Water Views",
    "Recently Renovated",
    "New Construction",
]
